### ISSUE TITLE
Scary error message when missing `module Main where`.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#1076]
I get a scary error message running `daml build` when my main module is missing the line `module Main where`:

```
$ daml build
Compiling daml/Main.daml to a DAR.
da-hs-damlc-app: user error (Creation of DAR file failed:
File:     daml/Main.daml
Range:    1:0-100001:0
Source:   Compiler
Severity: DsError
Message: 
  <Internal>: error:
  Compilation Issue: Internal error : module not found in NameCache :Main
  Please report this bug to the compiler authors.
Code: 
)
```

Here's `daml/Main.daml`:

```Daml
daml 1.2

mainScenario : Scenario ()
mainScenario = do
  pure ()
```

And here's `daml.yaml`:

```Yaml
sdk-version: 0.0.0
scenario: Main:mainScenario
dependencies:
- daml-prim
- daml-stdlib
exposed-modules:
- Main
name: foo
version: 1.0.0
source: daml/Main.daml
parties:
- Alice
- Bob
```

The error goes away when `module Main where` is added.
