### ISSUE TITLE
daml-ghc-test-all - Unicode.daml test failing on Windows

### ISSUE THREAD

**Issue by majcherm-da** [digital-asset/daml#1421]
`bazel test //daml-foundations/daml-ghc:daml-ghc-test-all` fails on `daml-foundations/daml-ghc/tests/Unicode.daml` test on Windows

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //daml-foundations/daml-ghc:daml-ghc-test-all
-----------------------------------------------------------------------------
rtsSupportsBoundThreads: True
getNumCapabilities: 2
rtsSupportsBoundThreads: True
getNumCapabilities: 2
rtsSupportsBoundThreads: True
getNumCapabilities: 2
rtsSupportsBoundThreads: True
getNumCapabilities: 2
All
  Uniques:                                                                               OK (0.02s)
  Tests for DAML-LF 1.1
    C:/users/e-mlmk/work/dah/projects/daml/daml-foundations/daml-ghc/tests\Unicode.daml: OK (6.85s)
      Time: GHC compile = 0.17s
      Time: Core pretty-printing = 0.01s
      Time: LF convert = 3.84s
      Time: LF pretty-printing = 0.01s
      Time: LF type check = 0.04s
      Time: LF saving = 0.00s
      Time: LF execution = 2.78s
      File:    
        C:/users/e-mlmk/work/dah/projects/daml/daml-foundations/daml-ghc/tests\Unicode.daml
      Range:    9:0-9:4
      Source:   Scenario
      Severity: DsError
      Message: 
        Scenario execution failed:
        Aborted: daml-ghc-test-all.exe: <stdout>: commitBuffer: invalid argument (invalid character)
```
