### ISSUE TITLE
`daml test` coverage report shows pecentages over 100 when using templates from dependencies

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#14309]
From the forums: https://discuss.daml.com/t/test-coverage-showing-as-greater-than-100/4811

Example:

```yaml
# dep/daml.yaml
sdk-version: 2.2.0
name: dep
source: Dep.daml
version: 0.0.1
dependencies:
  - daml-prim
  - daml-stdlib
  - daml-script
```

```haskell
-- dep/Dep.daml
module Dep where

import Daml.Script

template T0
  with
    party : Party
  where
    signatory party

run : Script ()
run = script do
  alice <- allocateParty "alice"
  c <- alice `submit` createCmd T0 with party = alice
  alice `submit` archiveCmd c
```

```yaml
# main/daml.yaml
sdk-version: 2.2.0
name: main
source: Main.daml
version: 0.0.1
dependencies:
  - daml-prim
  - daml-stdlib
  - daml-script
  - ../dep/.daml/dist/dep-0.0.1.dar
```

```haskell
-- main/Main.daml
module Main where

import Daml.Script
import Dep

template T1
  with
    party : Party
  where
    signatory party

run : Script ()
run = script do
  alice <- allocateParty "alice"
  c <- alice `submit` createCmd T0 with party = alice
  alice `submit` archiveCmd c
  c <- alice `submit` createCmd T1 with party = alice
  alice `submit` archiveCmd c
```

```bash
> DAML_PROJECT=dep daml build
> DAML_PROJECT=main daml build
> DAML_PROJECT=main daml test

Test Summary

Main.daml:run: ok, 0 active contracts, 4 transactions.
test coverage: templates 200%, choices 200%
```
