### ISSUE TITLE
`x : DA.Action.State.State s r` can't be used across data-dependencies

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#15744]
To reproduce, place `dd/daml.yaml`, `dd/DD.daml`, `main/daml.yaml` and `main/Main.daml` (see [Files](#Files)) in the same directory (keeping the structure) and run 

```bash
DAML_PROJECT=dd daml build && DAML_PROJECT=main daml build
```

It will fail with

```
• Couldn't match type
  ‘daml-stdlib-e81adc73d2eb58a675a5271de308de9a2a93d2c163a4f438a07459886f159ce8:DA.Action.State.State
  Bool’
  with ‘State Bool’
  NB: ‘State’
  is defined in ‘DA.Action.State’ in package ‘daml-stdlib-2.4.0’
  ‘daml-stdlib-e81adc73d2eb58a675a5271de308de9a2a93d2c163a4f438a07459886f159ce8:DA.Action.State.State’
  is defined in ‘DA.Action.State’
  in package ‘daml-stdlib-e81adc73d2eb58a675a5271de308de9a2a93d2c163a4f438a07459886f159ce8’
  Expected type: State Bool ()
  Actual type:
  daml-stdlib-e81adc73d2eb58a675a5271de308de9a2a93d2c163a4f438a07459886f159ce8:DA.Action.State.State
  Bool ()
```

### Files

```yaml
# dd/daml.yaml
sdk-version: 2.4.0
build-options: [--target=1.14]
name: dd
source: DD.daml
version: 0.0.1
dependencies:
  - daml-prim
  - daml-stdlib
```

```haskell
-- dd/DD.daml
module DD where

import DA.Action.State

stateful : State Bool ()
stateful = pure ()
```

```yaml
# main/daml.yaml
sdk-version: 2.4.0
build-options: [--target=1.15]
name: main
source: Main.daml
version: 0.0.1
dependencies:
  - daml-prim
  - daml-stdlib
data-dependencies:
  - ../dd/.daml/dist/dd-0.0.1.dar
```

```haskell
-- main/Main.daml
module Main where

import DD qualified
import DA.Action.State

stateful : State Bool ()
stateful = do
  DD.stateful
  pure ()
```
