### ISSUE TITLE
`daml repl` ignores `build-options: [--target=1.15]` from `daml.yaml`

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#15956]
to reproduce:

```yaml
# daml.yaml
sdk-version: 2.5.0
build-options: [--target=1.15]
name: example
version: 1.0.0
source: Main.daml
dependencies:
- daml-prim
- daml-stdlib
```

```haskell
-- Main.daml
module Main where

data V = V with
    u : ()
  deriving (Eq, Ord, Show)

interface I where
  viewtype V
```

```bash
daml build
daml repl .daml/dist/example-1.0.0.dar
```

## Expected result

Terminal shows `daml>` prompt with package loaded

## Actual result

the second command fails with

```
Targeted LF version 1.14 but dependencies have newer LF versions: 3622d3c3f5a78a06457a2811ebd4efac21a8f79842f951e92460294b5339658a (daml-stdlib-3622d3c3f5a78a06457a2811ebd4efac21a8f79842f951e92460294b5339658a): 1.15, 6df2d1fd8ea994ed048a79587b2722e3a887ac7592abf31ecf46fe09ac02d689 (daml-stdlib-DA-Internal-Interface-AnyView-Types-1.0.0): 1.15, a04a927810073d0466795c02c88b4f6bcaee5102bf6e1be46a35767fb50d4e6b (example-1.0.0): 1.15, e05767016083cf623599817f0076123c1a00bf8a0bfbb237101eeab70efd2091 (daml-prim-e05767016083cf623599817f0076123c1a00bf8a0bfbb237101eeab70efd2091): 1.15
```

## Notes

Explicitly giving the `--target=1.15` flag to `daml repl` works around the issue (but shouldn't be necessary since the flag is already in `daml.yaml`).

```
daml repl --target=1.15 .daml/dist/example-1.0.0.dar
```
