### ISSUE TITLE
Buggy exception handling in `daml3-script`

### ISSUE THREAD

**Issue by akrmn** [digital-asset/daml#18300]
This is the reincarnation of #16132, but on the new `daml3-script`. The problem is that a try-catch block is handled incorrectly in the `Script` DSL, so the `catch` scopes over the code _after_ the `try`

```yaml
# daml.yaml
sdk-version: 2.9.0-snapshot.20231220.0
build-options: [--target=2.dev]
name: d3s
source: Main.daml
version: 0.0.1
dependencies:
  - daml-prim
  - daml-stdlib
  - daml3-script
```

```haskell
-- Main.daml
module Main where

import Daml.Script
import DA.Assert
import DA.Exception

-- tests that the error from {- 6 -} doesn't get caught in {- 3 -} (#16132)
try_catch_then_error : Script ()
try_catch_then_error = do
  {- 1 -} wasThrown <-
  {- 2 -}   try do pure False
  {- 3 -}   catch (_ : AnyException) -> pure True
  {- 4 -} if wasThrown
  {- 5 -}   then pure ()
  {- 6 -}   else error "expected exception"
  ```
