### ISSUE TITLE
Give users more tools to deal with ghc package name shadowing in dependencies and data-dependencies.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#4948]
When packages have the same ghc package name, such as when importing multiple versions of the same package, or old versions of the current package, package qualified imports don't work by default. The user needs to a package flag in build-options to rename modules. This is really unintuitive, so I think we should add some support for dealing with package imports in `daml.yaml`, e.g. by giving the package an alias:

``` yaml
dependencies:
- daml-stdlib
- daml-prim
- package: foo-1.0.3
  alias: foo1
```

So you could disambiguate modules by using package qualified imports:

``` Haskell
import "foo1" Foo as Foo1
```

Alternatively, this could be solved by adding a prefix to module names:

``` yaml
dependencies:
- daml-stdlib
- daml-prim
- package: foo-1.0.3
  prefix: Foo1
```

so you can just use a regular import,

``` Haskell
import Foo1.Foo
```

I think the latter is a little cleaner for users, since you perform any necessary module renaming in a consistent place and you don't have to use package qualified import syntax, but I don't know which one is easier to implement.
