### ISSUE TITLE
DAML Script does not create intermediate directories for output file

### ISSUE THREAD

**Issue by Calyd** [digital-asset/daml#8142]
# Description

DAML Script accepts `--output-file` to write the results. Setting this to a path where the intermediate directories do not exist will result in a `java.nio.file.NoSuchFileException`.

## Steps to Reproduce

The `daml.yaml`:
```yaml
sdk-version: 1.7.0
name: failing-script
version: 1.0.0
source: FailingScript.daml
init-script: FailingScript:theAnswer
dependencies:
  - daml-prim
  - daml-stdlib
  - daml-script
```

The script itself:
```haskell
module FailingScript where

import Daml.Script

theAnswer : Script Int
theAnswer = pure 42
```

Make sure that `a/b/c` does not exist. The following command fails:
```shell
daml start --start-navigator false --json-api-port none  --script-option --output-file=a/b/c/theAnswer.json
```
