### ISSUE TITLE
Configuring trigger service to start triggers

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#9173]
**The problem**
Starting a couple of triggers via the Trigger Service requires programmatic steps:

1. get the package Id
2. (start the trigger service)
3. wait for the trigger service to open its port
4. start the triggers one by one via the Trigger Service API

In a simple demo app we would like to provide these in one single command to enable non-technical users.

**A workaround to be replaced**
Currently we're experimenting with a Python script along with some Daml Assistant helper functions.
See our workaround to start the triggers, i.e. solve the problem above in one command:  

- [startTriggers.py](https://github.com/digital-asset/ex-bond-issuance/blob/03abd9ac24213d5050797fecd24645af1a56c01e/scripts/startTriggers.py)  
- [damlassistant.py](https://github.com/digital-asset/ex-bond-issuance/blob/03abd9ac24213d5050797fecd24645af1a56c01e/scripts/damlassistant.py)  

But our code above adds complexity and this feature is likely repeatedly needed.

**Desired solution**
The triggers could be given in a configuration file, perhaps in `daml.yaml` like this:

```
triggers:
 - party: Bank1
   triggerName: DA.RefApps.Bond.Triggers.InvestorSettlementTrigger:investorSettlementTrigger
 - party: Bank2
   triggerName: DA.RefApps.Bond.Triggers.InvestorSettlementTrigger:investorSettlementTrigger
 - ...
 ```
 
Perhaps picked up by Daml trigger-service.
